/* eslint-disable */
// This file is auto-generated by TanStack Router.
// Manually created for initial setup — run `bun run dev` to auto-regenerate.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as LobbyCodeImport } from "./routes/lobby.$code";
import { Route as TeamCodeImport } from "./routes/team.$code";
import { Route as BattleCodeImport } from "./routes/battle.$code";
import { Route as PricingImport } from "./routes/pricing";

// .update() is required — createFileRoute does NOT embed path/getParentRoute
// in the route options; the auto-generator always calls update() to inject them.
const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const LobbyCodeRoute = LobbyCodeImport.update({
  path: '/lobby/$code',
  getParentRoute: () => rootRoute,
} as any);

const TeamCodeRoute = TeamCodeImport.update({
  path: '/team/$code',
  getParentRoute: () => rootRoute,
} as any);

const BattleCodeRoute = BattleCodeImport.update({
  path: '/battle/$code',
  getParentRoute: () => rootRoute,
} as any);

const PricingRoute = PricingImport.update({
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any);

const rootTree = rootRoute.addChildren([
  IndexRoute,
  LobbyCodeRoute,
  TeamCodeRoute,
  BattleCodeRoute,
  PricingRoute,
]);

export const routeTree = rootTree;

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { preLoaderRoute: typeof IndexRoute; parentRoute: typeof rootRoute };
    "/lobby/$code": { preLoaderRoute: typeof LobbyCodeRoute; parentRoute: typeof rootRoute };
    "/team/$code": { preLoaderRoute: typeof TeamCodeRoute; parentRoute: typeof rootRoute };
    "/battle/$code": { preLoaderRoute: typeof BattleCodeRoute; parentRoute: typeof rootRoute };
    "/pricing": { preLoaderRoute: typeof PricingRoute; parentRoute: typeof rootRoute };
  }
}
