/* eslint-disable */
// This file is auto-generated by TanStack Router.
// Manually created for initial setup — run `bun run dev` to auto-regenerate.

import { createRouter as createTanStackRouter } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as LobbyCodeRoute } from "./routes/lobby.$code";
import { Route as TeamCodeRoute } from "./routes/team.$code";
import { Route as BattleCodeRoute } from "./routes/battle.$code";

const rootTree = rootRoute.addChildren([
  IndexRoute,
  LobbyCodeRoute,
  TeamCodeRoute,
  BattleCodeRoute,
]);

export const routeTree = rootTree;

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { preLoaderRoute: typeof IndexRoute; parentRoute: typeof rootRoute };
    "/lobby/$code": { preLoaderRoute: typeof LobbyCodeRoute; parentRoute: typeof rootRoute };
    "/team/$code":  { preLoaderRoute: typeof TeamCodeRoute;  parentRoute: typeof rootRoute };
    "/battle/$code": { preLoaderRoute: typeof BattleCodeRoute; parentRoute: typeof rootRoute };
  }
}
